dist: trusty
sudo: required
language: crystal

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

script:
  - bin/ameba ./src
  - crystal spec ./spec/maze
  - crystal spec ./spec/build_spec.cr -D run_build_tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

