version: '2'
services:
  db:
    image: postgres:10.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_app_development
  redis:
    image: redis:3.2-alpine
    command: redis-server
  spec:
    build: .
    working_dir: /opt/maze
    environment:
      REDIS_URL: 'redis://redis:6379'
      MAZE_ENV: test
      CI: "false"
    depends_on:
      - redis
      - db
